//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowGoods", ReplyAction="http://tempuri.org/IService1/ShowGoodsResponse")]
        ClassLibrary1.Goods ShowGoods(ClassLibrary1.Transfer a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowGoods", ReplyAction="http://tempuri.org/IService1/ShowGoodsResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Goods> ShowGoodsAsync(ClassLibrary1.Transfer a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Show", ReplyAction="http://tempuri.org/IService1/ShowResponse")]
        ClassLibrary1.Goods Show();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Show", ReplyAction="http://tempuri.org/IService1/ShowResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Goods> ShowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_good", ReplyAction="http://tempuri.org/IService1/get_goodResponse")]
        ClassLibrary1.Good get_good(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_good", ReplyAction="http://tempuri.org/IService1/get_goodResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Good> get_goodAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getorder", ReplyAction="http://tempuri.org/IService1/getorderResponse")]
        void getorder(ClassLibrary1.Order ord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getorder", ReplyAction="http://tempuri.org/IService1/getorderResponse")]
        System.Threading.Tasks.Task getorderAsync(ClassLibrary1.Order ord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_good", ReplyAction="http://tempuri.org/IService1/add_goodResponse")]
        void add_good(ClassLibrary1.Good x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_good", ReplyAction="http://tempuri.org/IService1/add_goodResponse")]
        System.Threading.Tasks.Task add_goodAsync(ClassLibrary1.Good x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_good", ReplyAction="http://tempuri.org/IService1/edit_goodResponse")]
        void edit_good(ClassLibrary1.Good good);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_good", ReplyAction="http://tempuri.org/IService1/edit_goodResponse")]
        System.Threading.Tasks.Task edit_goodAsync(ClassLibrary1.Good good);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_good", ReplyAction="http://tempuri.org/IService1/del_goodResponse")]
        void del_good(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_good", ReplyAction="http://tempuri.org/IService1/del_goodResponse")]
        System.Threading.Tasks.Task del_goodAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_group", ReplyAction="http://tempuri.org/IService1/get_groupResponse")]
        ClassLibrary1.Groups get_group();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_group", ReplyAction="http://tempuri.org/IService1/get_groupResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Groups> get_groupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_metall", ReplyAction="http://tempuri.org/IService1/get_metallResponse")]
        ClassLibrary1.Metalls get_metall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_metall", ReplyAction="http://tempuri.org/IService1/get_metallResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Metalls> get_metallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_group", ReplyAction="http://tempuri.org/IService1/add_groupResponse")]
        void add_group(string name, string c_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_group", ReplyAction="http://tempuri.org/IService1/add_groupResponse")]
        System.Threading.Tasks.Task add_groupAsync(string name, string c_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_group", ReplyAction="http://tempuri.org/IService1/del_groupResponse")]
        void del_group(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_group", ReplyAction="http://tempuri.org/IService1/del_groupResponse")]
        System.Threading.Tasks.Task del_groupAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_group", ReplyAction="http://tempuri.org/IService1/edit_groupResponse")]
        void edit_group(int id, string name, string c_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_group", ReplyAction="http://tempuri.org/IService1/edit_groupResponse")]
        System.Threading.Tasks.Task edit_groupAsync(int id, string name, string c_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_metall", ReplyAction="http://tempuri.org/IService1/add_metallResponse")]
        void add_metall(string name, string m_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_metall", ReplyAction="http://tempuri.org/IService1/add_metallResponse")]
        System.Threading.Tasks.Task add_metallAsync(string name, string m_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_metall", ReplyAction="http://tempuri.org/IService1/del_metallResponse")]
        void del_metall(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_metall", ReplyAction="http://tempuri.org/IService1/del_metallResponse")]
        System.Threading.Tasks.Task del_metallAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_metall", ReplyAction="http://tempuri.org/IService1/edit_metallResponse")]
        void edit_metall(int id, string name, string m_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_metall", ReplyAction="http://tempuri.org/IService1/edit_metallResponse")]
        System.Threading.Tasks.Task edit_metallAsync(int id, string name, string m_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_order", ReplyAction="http://tempuri.org/IService1/add_orderResponse")]
        void add_order(string FN, string SN, string TN, long ph, int id_buy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_order", ReplyAction="http://tempuri.org/IService1/add_orderResponse")]
        System.Threading.Tasks.Task add_orderAsync(string FN, string SN, string TN, long ph, int id_buy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/remove_order", ReplyAction="http://tempuri.org/IService1/remove_orderResponse")]
        void remove_order(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/remove_order", ReplyAction="http://tempuri.org/IService1/remove_orderResponse")]
        System.Threading.Tasks.Task remove_orderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_sale", ReplyAction="http://tempuri.org/IService1/get_saleResponse")]
        ClassLibrary1.Sales get_sale(bool check);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_sale", ReplyAction="http://tempuri.org/IService1/get_saleResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Sales> get_saleAsync(bool check);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_sale", ReplyAction="http://tempuri.org/IService1/add_saleResponse")]
        void add_sale(ClassLibrary1.Order ord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_sale", ReplyAction="http://tempuri.org/IService1/add_saleResponse")]
        System.Threading.Tasks.Task add_saleAsync(ClassLibrary1.Order ord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/done_sale", ReplyAction="http://tempuri.org/IService1/done_saleResponse")]
        void done_sale(int s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/done_sale", ReplyAction="http://tempuri.org/IService1/done_saleResponse")]
        System.Threading.Tasks.Task done_saleAsync(int s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_order", ReplyAction="http://tempuri.org/IService1/get_orderResponse")]
        ClassLibrary1.Orders get_order();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_order", ReplyAction="http://tempuri.org/IService1/get_orderResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Orders> get_orderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/remove_sale", ReplyAction="http://tempuri.org/IService1/remove_saleResponse")]
        void remove_sale(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/remove_sale", ReplyAction="http://tempuri.org/IService1/remove_saleResponse")]
        System.Threading.Tasks.Task remove_saleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_user", ReplyAction="http://tempuri.org/IService1/add_userResponse")]
        void add_user(string FN, string SN, string TN, long phone, string data, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_user", ReplyAction="http://tempuri.org/IService1/add_userResponse")]
        System.Threading.Tasks.Task add_userAsync(string FN, string SN, string TN, long phone, string data, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checklogin", ReplyAction="http://tempuri.org/IService1/checkloginResponse")]
        bool checklogin(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checklogin", ReplyAction="http://tempuri.org/IService1/checkloginResponse")]
        System.Threading.Tasks.Task<bool> checkloginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_user", ReplyAction="http://tempuri.org/IService1/get_userResponse")]
        ClassLibrary1.customer get_user(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_user", ReplyAction="http://tempuri.org/IService1/get_userResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.customer> get_userAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/remove_user", ReplyAction="http://tempuri.org/IService1/remove_userResponse")]
        void remove_user(ClassLibrary1.customer cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/remove_user", ReplyAction="http://tempuri.org/IService1/remove_userResponse")]
        System.Threading.Tasks.Task remove_userAsync(ClassLibrary1.customer cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_proba", ReplyAction="http://tempuri.org/IService1/get_probaResponse")]
        ClassLibrary1.probas get_proba();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_proba", ReplyAction="http://tempuri.org/IService1/get_probaResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.probas> get_probaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_proba", ReplyAction="http://tempuri.org/IService1/add_probaResponse")]
        void add_proba(ClassLibrary1.proba x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_proba", ReplyAction="http://tempuri.org/IService1/add_probaResponse")]
        System.Threading.Tasks.Task add_probaAsync(ClassLibrary1.proba x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_stone", ReplyAction="http://tempuri.org/IService1/get_stoneResponse")]
        ClassLibrary1.Stones get_stone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_stone", ReplyAction="http://tempuri.org/IService1/get_stoneResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Stones> get_stoneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_stone", ReplyAction="http://tempuri.org/IService1/edit_stoneResponse")]
        void edit_stone(int id, string name, string c_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_stone", ReplyAction="http://tempuri.org/IService1/edit_stoneResponse")]
        System.Threading.Tasks.Task edit_stoneAsync(int id, string name, string c_k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_stone", ReplyAction="http://tempuri.org/IService1/del_stoneResponse")]
        void del_stone(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_stone", ReplyAction="http://tempuri.org/IService1/del_stoneResponse")]
        System.Threading.Tasks.Task del_stoneAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_Stone", ReplyAction="http://tempuri.org/IService1/add_StoneResponse")]
        void add_Stone(ClassLibrary1.Stone x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_Stone", ReplyAction="http://tempuri.org/IService1/add_StoneResponse")]
        System.Threading.Tasks.Task add_StoneAsync(ClassLibrary1.Stone x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_proba", ReplyAction="http://tempuri.org/IService1/del_probaResponse")]
        void del_proba(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/del_proba", ReplyAction="http://tempuri.org/IService1/del_probaResponse")]
        System.Threading.Tasks.Task del_probaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_proba", ReplyAction="http://tempuri.org/IService1/edit_probaResponse")]
        void edit_proba(int id, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edit_proba", ReplyAction="http://tempuri.org/IService1/edit_probaResponse")]
        System.Threading.Tasks.Task edit_probaAsync(int id, string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Seller.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Seller.ServiceReference1.IService1>, Seller.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClassLibrary1.Goods ShowGoods(ClassLibrary1.Transfer a) {
            return base.Channel.ShowGoods(a);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Goods> ShowGoodsAsync(ClassLibrary1.Transfer a) {
            return base.Channel.ShowGoodsAsync(a);
        }
        
        public ClassLibrary1.Goods Show() {
            return base.Channel.Show();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Goods> ShowAsync() {
            return base.Channel.ShowAsync();
        }
        
        public ClassLibrary1.Good get_good(int id) {
            return base.Channel.get_good(id);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Good> get_goodAsync(int id) {
            return base.Channel.get_goodAsync(id);
        }
        
        public void getorder(ClassLibrary1.Order ord) {
            base.Channel.getorder(ord);
        }
        
        public System.Threading.Tasks.Task getorderAsync(ClassLibrary1.Order ord) {
            return base.Channel.getorderAsync(ord);
        }
        
        public void add_good(ClassLibrary1.Good x) {
            base.Channel.add_good(x);
        }
        
        public System.Threading.Tasks.Task add_goodAsync(ClassLibrary1.Good x) {
            return base.Channel.add_goodAsync(x);
        }
        
        public void edit_good(ClassLibrary1.Good good) {
            base.Channel.edit_good(good);
        }
        
        public System.Threading.Tasks.Task edit_goodAsync(ClassLibrary1.Good good) {
            return base.Channel.edit_goodAsync(good);
        }
        
        public void del_good(int id) {
            base.Channel.del_good(id);
        }
        
        public System.Threading.Tasks.Task del_goodAsync(int id) {
            return base.Channel.del_goodAsync(id);
        }
        
        public ClassLibrary1.Groups get_group() {
            return base.Channel.get_group();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Groups> get_groupAsync() {
            return base.Channel.get_groupAsync();
        }
        
        public ClassLibrary1.Metalls get_metall() {
            return base.Channel.get_metall();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Metalls> get_metallAsync() {
            return base.Channel.get_metallAsync();
        }
        
        public void add_group(string name, string c_k) {
            base.Channel.add_group(name, c_k);
        }
        
        public System.Threading.Tasks.Task add_groupAsync(string name, string c_k) {
            return base.Channel.add_groupAsync(name, c_k);
        }
        
        public void del_group(int id) {
            base.Channel.del_group(id);
        }
        
        public System.Threading.Tasks.Task del_groupAsync(int id) {
            return base.Channel.del_groupAsync(id);
        }
        
        public void edit_group(int id, string name, string c_k) {
            base.Channel.edit_group(id, name, c_k);
        }
        
        public System.Threading.Tasks.Task edit_groupAsync(int id, string name, string c_k) {
            return base.Channel.edit_groupAsync(id, name, c_k);
        }
        
        public void add_metall(string name, string m_k) {
            base.Channel.add_metall(name, m_k);
        }
        
        public System.Threading.Tasks.Task add_metallAsync(string name, string m_k) {
            return base.Channel.add_metallAsync(name, m_k);
        }
        
        public void del_metall(int id) {
            base.Channel.del_metall(id);
        }
        
        public System.Threading.Tasks.Task del_metallAsync(int id) {
            return base.Channel.del_metallAsync(id);
        }
        
        public void edit_metall(int id, string name, string m_k) {
            base.Channel.edit_metall(id, name, m_k);
        }
        
        public System.Threading.Tasks.Task edit_metallAsync(int id, string name, string m_k) {
            return base.Channel.edit_metallAsync(id, name, m_k);
        }
        
        public void add_order(string FN, string SN, string TN, long ph, int id_buy) {
            base.Channel.add_order(FN, SN, TN, ph, id_buy);
        }
        
        public System.Threading.Tasks.Task add_orderAsync(string FN, string SN, string TN, long ph, int id_buy) {
            return base.Channel.add_orderAsync(FN, SN, TN, ph, id_buy);
        }
        
        public void remove_order(int id) {
            base.Channel.remove_order(id);
        }
        
        public System.Threading.Tasks.Task remove_orderAsync(int id) {
            return base.Channel.remove_orderAsync(id);
        }
        
        public ClassLibrary1.Sales get_sale(bool check) {
            return base.Channel.get_sale(check);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Sales> get_saleAsync(bool check) {
            return base.Channel.get_saleAsync(check);
        }
        
        public void add_sale(ClassLibrary1.Order ord) {
            base.Channel.add_sale(ord);
        }
        
        public System.Threading.Tasks.Task add_saleAsync(ClassLibrary1.Order ord) {
            return base.Channel.add_saleAsync(ord);
        }
        
        public void done_sale(int s) {
            base.Channel.done_sale(s);
        }
        
        public System.Threading.Tasks.Task done_saleAsync(int s) {
            return base.Channel.done_saleAsync(s);
        }
        
        public ClassLibrary1.Orders get_order() {
            return base.Channel.get_order();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Orders> get_orderAsync() {
            return base.Channel.get_orderAsync();
        }
        
        public void remove_sale(int id) {
            base.Channel.remove_sale(id);
        }
        
        public System.Threading.Tasks.Task remove_saleAsync(int id) {
            return base.Channel.remove_saleAsync(id);
        }
        
        public void add_user(string FN, string SN, string TN, long phone, string data, string login, string password) {
            base.Channel.add_user(FN, SN, TN, phone, data, login, password);
        }
        
        public System.Threading.Tasks.Task add_userAsync(string FN, string SN, string TN, long phone, string data, string login, string password) {
            return base.Channel.add_userAsync(FN, SN, TN, phone, data, login, password);
        }
        
        public bool checklogin(string login, string password) {
            return base.Channel.checklogin(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> checkloginAsync(string login, string password) {
            return base.Channel.checkloginAsync(login, password);
        }
        
        public ClassLibrary1.customer get_user(string login, string password) {
            return base.Channel.get_user(login, password);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.customer> get_userAsync(string login, string password) {
            return base.Channel.get_userAsync(login, password);
        }
        
        public void remove_user(ClassLibrary1.customer cus) {
            base.Channel.remove_user(cus);
        }
        
        public System.Threading.Tasks.Task remove_userAsync(ClassLibrary1.customer cus) {
            return base.Channel.remove_userAsync(cus);
        }
        
        public ClassLibrary1.probas get_proba() {
            return base.Channel.get_proba();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.probas> get_probaAsync() {
            return base.Channel.get_probaAsync();
        }
        
        public void add_proba(ClassLibrary1.proba x) {
            base.Channel.add_proba(x);
        }
        
        public System.Threading.Tasks.Task add_probaAsync(ClassLibrary1.proba x) {
            return base.Channel.add_probaAsync(x);
        }
        
        public ClassLibrary1.Stones get_stone() {
            return base.Channel.get_stone();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Stones> get_stoneAsync() {
            return base.Channel.get_stoneAsync();
        }
        
        public void edit_stone(int id, string name, string c_k) {
            base.Channel.edit_stone(id, name, c_k);
        }
        
        public System.Threading.Tasks.Task edit_stoneAsync(int id, string name, string c_k) {
            return base.Channel.edit_stoneAsync(id, name, c_k);
        }
        
        public void del_stone(int id) {
            base.Channel.del_stone(id);
        }
        
        public System.Threading.Tasks.Task del_stoneAsync(int id) {
            return base.Channel.del_stoneAsync(id);
        }
        
        public void add_Stone(ClassLibrary1.Stone x) {
            base.Channel.add_Stone(x);
        }
        
        public System.Threading.Tasks.Task add_StoneAsync(ClassLibrary1.Stone x) {
            return base.Channel.add_StoneAsync(x);
        }
        
        public void del_proba(int id) {
            base.Channel.del_proba(id);
        }
        
        public System.Threading.Tasks.Task del_probaAsync(int id) {
            return base.Channel.del_probaAsync(id);
        }
        
        public void edit_proba(int id, string number) {
            base.Channel.edit_proba(id, number);
        }
        
        public System.Threading.Tasks.Task edit_probaAsync(int id, string number) {
            return base.Channel.edit_probaAsync(id, number);
        }
    }
}
